M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date Thu 03 Feb 2022 01:14:25 PM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-03T13:14:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X-46.5Y0.0
X-46.5Y-55.0
X-46.5Y-94.0
X46.5Y0.0
X46.5Y-55.0
X46.5Y-94.0
T0
M30
